---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $VC_INDEX-teku
  name: $VC_INDEX-teku
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $VC_INDEX-teku
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: $VC_INDEX-teku
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
        - name: init-chown
          image: busybox
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -ac
            - >
              rm -rf /data/teku/validator_keys 2>/dev/null || true;
              mkdir -p /data/teku/validator_keys;
              cp /validator_keys/* /data/teku/validator_keys;
              chown -R 1000:1000 /data/teku;
          volumeMounts:
            - name: data
              mountPath: /data/teku
            - name: validators
              mountPath: "/validator_keys"
      containers:
        - name: $VC_INDEX-teku
          image: consensys/teku:$TEKU_VERSION
          command:
            - sh
            - -ace
            - |
              /opt/teku/bin/teku vc \
              --network=auto \
              --log-destination=console \
              --data-base-path=/data/teku \
              --metrics-enabled=true \
              --metrics-host-allowlist="*" \
              --metrics-interface="0.0.0.0" \
              --metrics-port="8008" \
              --validator-keys="/data/teku/validator_keys:/data/teku/validator_keys" \
              --validators-graffiti="Obol Distributed Validator" \
              --beacon-node-api-endpoint="http://$NODE_NAME:3600" \
              --validators-proposer-default-fee-recipient="0x9FD17880D4F5aE131D62CE6b48dF7ba7D426a410";
          volumeMounts:
            - name: validators
              mountPath: /charon/$NODE_NAME/validator_keys
            - name: private-key
              mountPath: /charon/$NODE_NAME
            - name: cluster-lock
              mountPath: /charon
            - name: data
              mountPath: /data/teku
      volumes:
        - name: validators
          projected:
            sources:
            - secret:
                name: $NODE_NAME-validators
        - name: private-key
          projected:
            sources:
            - secret:
                name: $NODE_NAME-charon-enr-private-key
        - name: cluster-lock
          projected:
            sources:
            - secret:
                name: cluster-lock
        - name: data
          persistentVolumeClaim:
            claimName: $CLUSTER_NAME-$VC_INDEX-teku-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: $VC_INDEX-teku
  namespace: $CLUSTER_NAME
spec:
  selector:
    app: $VC_INDEX-teku
  ports:
  ports:
    - name: metrics
      protocol: TCP
      port: 8008
      targetPort: 8008
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $CLUSTER_NAME-$VC_INDEX-teku-pv
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/data
  persistentVolumeReclaimPolicy: Delete
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: $CLUSTER_NAME-$VC_INDEX-teku-pvc
      namespace: $CLUSTER_NAME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: $CLUSTER_NAME-$VC_INDEX-teku-pvc
  namespace: $CLUSTER_NAME
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
